'use strict';
require('dotenv').config();
const express=require('express');
const cors=require('cors');
const jwt=require('jsonwebtoken');
const cron=require('node-cron');
const crypto=require('crypto');
const {runSora}=require('./agents/sora');
const {runDeep}=require('./agents/deep');
const {runGold}=require('./agents/gold');
const {fbGet,fbSet,fbUpdate,logEvent,notifyOwner,DEFAULT_SETTINGS}=require('./agents/utils');
const app=express();
const PORT=process.env.PORT||3000;
const JWT_SECRET=crypto.createHash('sha256').update(process.env.DASHBOARD_PIN+':'+process.env.ANTHROPIC_API_KEY+':sdg-2025').digest('hex');
const MONTHLY_BUDGET=parseFloat(process.env.MONTHLY_BUDGET_SAR||'230');
const loginAttempts=new Map();
let cronJobs={};
app.use(cors());
app.use(express.json());
function isNew(s){return !s||s==='new'||s.includes('جديد')||s.includes('jdyd')}function isSent(s){return s==='sent'||s.includes('أُرسل')}function isReply(s){return s==='reply'||s.includes('ردّ')}function isClient(s){return s==='client'||s.includes('عميل')}
function requireAuth(req,res,next){const token=req.headers.authorization?.replace('Bearer ','');if(!token)return res.status(401).json({error:'ظٹظ„ط²ظ… طھط³ط¬ظٹظ„ ط§ظ„ط¯ط®ظˆظ„'});try{req.user=jwt.verify(token,JWT_SECRET);next();}catch{res.status(401).json({error:'ط¬ظ„ط³ط© ظ…ظ†طھظ‡ظٹط©'});}}
function timeToCron(hhmm,days){const[h,m]=hhmm.split(':').map(Number);const map={sunday:0,monday:1,tuesday:2,wednesday:3,thursday:4,friday:5,saturday:6};const nums=Object.entries(days).filter(([,on])=>on).map(([d])=>map[d]).sort().join(',');return m+' '+h+' * * '+(nums||'0-6');}
async function initSchedule(){Object.values(cronJobs).forEach(j=>j?.destroy?.());cronJobs={};try{const s=await fbGet('settings')||DEFAULT_SETTINGS;const sch=s.schedule||DEFAULT_SETTINGS.schedule;const day=s.days||DEFAULT_SETTINGS.days;cronJobs.sora=cron.schedule(timeToCron(sch.soraStart||'08:00',day),async()=>{const c=await fbGet('settings');if(c?.mode==='manual')return;await runSora();},{timezone:'Asia/Riyadh'});cronJobs.deep=cron.schedule(timeToCron(sch.deepStart||'10:00',day),async()=>{const c=await fbGet('settings');if(c?.mode==='manual')return;await runDeep();},{timezone:'Asia/Riyadh'});cronJobs.gold=cron.schedule(timeToCron(sch.goldStart||'20:00',day),async()=>{const c=await fbGet('settings');if(c?.mode==='manual')return;await runGold();},{timezone:'Asia/Riyadh'});}catch(e){cronJobs.sora=cron.schedule('0 8 * * 0-5',()=>runSora(),{timezone:'Asia/Riyadh'});cronJobs.deep=cron.schedule('0 10 * * 0-5',()=>runDeep(),{timezone:'Asia/Riyadh'});cronJobs.gold=cron.schedule('0 20 * * 0-5',()=>runGold(),{timezone:'Asia/Riyadh'});}}
app.post('/api/auth/login',(req,res)=>{const{pin}=req.body;const ip=req.ip;const now=Date.now();const att=loginAttempts.get(ip)||{count:0,at:0};if(att.count>=5&&now-att.at<15*60*1000){const mins=Math.ceil((15*60*1000-(now-att.at))/60000);return res.status(429).json({error:'ط­ط§ظˆظ„ ط¨ط¹ط¯ '+mins+' ط¯ظ‚ظٹظ‚ط©'});}if(!pin||String(pin)!==String(process.env.DASHBOARD_PIN)){loginAttempts.set(ip,{count:att.count+1,at:now});return res.status(401).json({error:'ط±ظ…ط² ط®ط§ط·ط¦'});}loginAttempts.delete(ip);const token=jwt.sign({role:'owner'},JWT_SECRET,{expiresIn:'7d'});res.json({token});});
app.get('/api/stats',requireAuth,async(req,res)=>{try{const[leads,outreach,settings]=await Promise.all([fbGet('leads'),fbGet('outreach'),fbGet('settings')]);const la=Object.values(leads||{});const oa=Object.values(outreach||{});const tod=new Date().toISOString().split('T')[0];res.json({total:{leads:la.length,sent:la.filter(l=>['ط£ظڈط±ط³ظ„','ط±ط¯ظ‘','ط¹ظ…ظٹظ„'].includes(l.status)).length,replies:oa.filter(o=>o.status==='ط±ط¯ظ‘').length,clients:la.filter(l=>l.status==='ط¹ظ…ظٹظ„').length},today:{discovered:la.filter(l=>l.discoveredAt?.startsWith(tod)).length,sent:oa.filter(o=>o.sentAt?.startsWith(tod)).length,replies:oa.filter(o=>o.repliedAt?.startsWith(tod)).length},budget:{used:settings?.budgetUsed||0,limit:MONTHLY_BUDGET,remaining:MONTHLY_BUDGET-(settings?.budgetUsed||0)},byStatus:{new:la.filter(l=>l.status==='ط¬ط¯ظٹط¯').length,sent:la.filter(l=>l.status==='ط£ظڈط±ط³ظ„').length,replied:la.filter(l=>l.status==='ط±ط¯ظ‘').length,client:la.filter(l=>l.status==='ط¹ظ…ظٹظ„').length}});}catch(e){res.status(500).json({error:e.message});}});
app.get('/api/settings',requireAuth,async(req,res)=>{try{res.json(await fbGet('settings')||DEFAULT_SETTINGS);}catch(e){res.status(500).json({error:e.message});}});
app.put('/api/settings',requireAuth,async(req,res)=>{try{await fbUpdate('settings',req.body);if(req.body.schedule||req.body.days)await initSchedule();res.json({success:true,message:'طھظ… ط§ظ„ط­ظپط¸'});}catch(e){res.status(500).json({error:e.message});}});
app.get('/api/leads',requireAuth,async(req,res)=>{try{const{status,limit=50,offset=0}=req.query;const all=await fbGet('leads')||{};let list=Object.entries(all).map(([id,d])=>({id,...d}));if(status)list=list.filter(l=>l.status===status);list.sort((a,b)=>new Date(b.discoveredAt)-new Date(a.discoveredAt));res.json({total:list.length,leads:list.slice(Number(offset),Number(offset)+Number(limit))});}catch(e){res.status(500).json({error:e.message});}});
app.put('/api/leads/:id',requireAuth,async(req,res)=>{try{await fbUpdate('leads/'+req.params.id,req.body);res.json({success:true});}catch(e){res.status(500).json({error:e.message});}});
app.delete('/api/leads/:id',requireAuth,async(req,res)=>{try{const all=await fbGet('leads')||{};delete all[req.params.id];await fbSet('leads',all);res.json({success:true});}catch(e){res.status(500).json({error:e.message});}});
app.post('/api/agents/sora/run',requireAuth,(req,res)=>{res.json({success:true,message:'ط³ظˆط±ط§ ظٹط¹ظ…ظ„...'});runSora(req.body).catch(e=>logEvent('error','ط³ظˆط±ط§',{error:e.message}));});
app.post('/api/agents/deep/run',requireAuth,(req,res)=>{res.json({success:true,message:'ط¯ظٹط¨ ظٹط¹ظ…ظ„...'});runDeep(req.body).catch(e=>logEvent('error','ط¯ظٹط¨',{error:e.message}));});
app.post('/api/agents/gold/run',requireAuth,(req,res)=>{res.json({success:true,message:'ط¬ظˆظ„ط¯ ظٹط¹ظ…ظ„...'});runGold().catch(e=>logEvent('error','ط¬ظˆظ„ط¯',{error:e.message}));});
app.get('/api/reports',requireAuth,async(req,res)=>{try{const all=await fbGet('reports')||{};const list=Object.entries(all).map(([date,d])=>({date,...d})).sort((a,b)=>b.date.localeCompare(a.date)).slice(0,30);res.json(list);}catch(e){res.status(500).json({error:e.message});}});
app.post('/api/leads/:id/email',requireAuth,async(req,res)=>{try{const leads=await fbGet('leads')||{};const lead=leads[req.params.id];if(!lead)return res.status(404).json({error:'ظ„ط§ طھظˆط¬ط¯'});if(!lead.email)return res.status(400).json({error:'ظ„ط§ ظٹظˆط¬ط¯ ط¥ظٹظ…ظٹظ„'});const nodemailer=require('nodemailer');const t=nodemailer.createTransport({service:'gmail',auth:{user:process.env.GMAIL_USER,pass:process.env.GMAIL_PASS}});const msg=req.body.message||'ط§ظ„ط³ظ„ط§ظ… ط¹ظ„ظٹظƒظ…طŒ\n\nظ†ط­ظ† ظ…ظ† ظپط±ظٹظ‚ VOLT STORE ط§ظ„ظ…طھط®طµطµ ظپظٹ طھطµظ…ظٹظ… ط§ظ„ظ…ظˆط§ظ‚ط¹.\n\nظ†ظˆط¯ ظ…ط³ط§ط¹ط¯ط© '+lead.name+' ظپظٹ ط¨ظ†ط§ط، ظ…ظˆظ‚ط¹ ط§ط­طھط±ط§ظپظٹ.\n\nظ†ظ‚ط¯ظ…:\nâœ… طھطµظ…ظٹظ… ظ…ظˆظ‚ط¹ ط§ط­طھط±ط§ظپظٹ\nâœ… ط¸ظ‡ظˆط± ظپظٹ Google\nâœ… ط¯ط¹ظ… ظپظ†ظٹ\n\nظ‡ظ„ ظٹظ…ظƒظ†ظ†ط§ ط§ظ„طھط­ط¯ط«طں';await t.sendMail({from:'VOLT STORE <'+process.env.GMAIL_USER+'>',to:lead.email,subject:'ط¹ط±ط¶ ط®ط§طµ ظ„ظ€ '+lead.name,text:msg,html:'<div dir=rtl style=font-family:Arial,sans-serif;padding:24px><h2 style=color:#6366f1>'+lead.name+'</h2><p style=color:#64748b>'+lead.category+' آ· '+lead.city+'</p><div style=background:#f8fafc;padding:18px;border-radius:8px;border-right:4px solid #6366f1;line-height:2>'+msg.replace(/\n/g,'<br>')+'</div></div>'});await fbUpdate('leads/'+req.params.id,{status:'ط£ظڈط±ط³ظ„',sentAt:new Date().toISOString()});res.json({success:true});}catch(e){res.status(500).json({error:e.message});}});
app.get('/health',(_,res)=>res.json({status:'ok',time:new Date().toISOString()}));
app.listen(PORT,async()=>{console.log('TRIPLE AGENTS ظ…ظ†ظپط° '+PORT);try{const e=await fbGet('settings');if(!e)await fbSet('settings',DEFAULT_SETTINGS);}catch{}await initSchedule();});


